name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node.js, npm, and dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # ou une autre version si nécessaire

      - name: Install dependencies
        run: npm install

      # Build the project (Assuming a build script is defined in package.json)
      - name: Build the project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Assurez-vous que cela pointe vers votre répertoire de build
